[package]
name = "life"
version = "0.1.0"
edition = "2021"
authors = ["Oghenemarho Orukele <orukele.dev@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
termion = "1.5.6"